### ISSUE TITLE
Highlighting Concordia Buildings 

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#11]
# User Story 

## WHO/WHAT/WHY
* As a user, I want to see my buildings highlighted so that I can easily distinguish them.

## ACCEPTANCE CRITERIA
* Shows Highlighted Indication for all Concordia Buildings on Google Maps
* Tap Event when clicking on building

## IMPLEMENTATION NOTES
http://www.concordia.ca/maps/loyola-campus.html
http://www.concordia.ca/maps/sgw-campus.html

**Comment by MoreWaqar** [comment]
Completed and awaiting review

**Comment by DBatistaFerreira** [comment]
**Acceptance Testing Passed ✅**

_SGW Buildings Highlighted and Tap Event:_
B ✅CB ✅CI ✅CL ✅D ✅EN ✅ER ✅EV ✅FA ✅FB ✅FG ✅
GM✅GN ✅GS ✅H ✅K ✅LB ✅LD ✅LS ✅M ✅ MB ✅MI ✅MU ✅P ✅PR ✅Q ✅R ✅RR ✅S ✅SB ✅T ✅TD ✅V ✅VA ✅
X ❌
Z ❌
GA ❌

_Loyola Buildings Highlighted and Tap Event:_
AD ✅BB ✅BH ✅CC ✅CJ ✅DO ✅FC ✅GE ✅HA ✅HB ✅HC ✅HU ✅JR ✅PC ✅PS ✅PT ✅PY ✅RA ✅RF ✅SC ✅SI ✅ SP ✅TA ✅VE ✅VL ✅
SH ❌Left out because of no coordinates on google maps and no class room ✅
QA ❌ Left out because of no coordinates on google maps and no class room ✅

_Bugs Found_
Highlighting Coordinates and Pop Up Information Missing Buildings #45
Highlighted Buildings Vertices are off #46
