### ISSUE TITLE
Building Pop Up Information

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#12]
# User Story 

## WHO/WHAT/WHY
* As a user, I want to learn about the buildings or see their information

## ACCEPTANCE CRITERIA
* When highlighted building is clicked on map information pop up is opened
* Shows information about the building
-- Address
-- Phone
-- Website
-- Opening Hours
* Button for directions to the building (GO)

**Comment by MoreWaqar** [comment]
![image](https://user-images.githubusercontent.com/35977219/74764594-fdaba500-524f-11ea-8c82-84baf0362971.png)


Buttons Featured in Mockup
--
ID | Goal
1 | To get to the itinerary page and set the destination point to the building selected
2 | To open the browser with the indicated address

**Comment by neliop** [comment]
**So far,**

We decided to use a persistent bottom sheet for the building info. This lets the user interact with the map and other UI elements while the sheet is visible.

The method to show the sheet returns a controller for it, so we used this controller to close the sheet when the map is tapped.

Tapping the website URL opens it in the device's default browser.

**What's left?**

We still need to add the opening hours to the constants file and figure out how to show them on the sheet. A collapsible widget could work.

I'm also going to see about using a bloc to receive events that should trigger the info sheet and update the sheet's info. This'll make it easy to trigger the sheet with both Marker and Polygon taps.

**Comment by neliop** [comment]
Implemented a new bloc (BuildingInfoBloc) to receive events whenever the info sheet should be displayed/updated. Marker and Polygon taps now both send these events.

Expanding/collapsing Opening Hours also triggers an event and the height of the Container that the sheet is in changes to one of two values which are both percentages of the device's screen height. There's probably a better way to handle the sizing of the Container/sheet, but I'm not sure.

The website and phone number list tiles both have onTap functions that open the website/number in the device's browser and phone app, respectively.

**What's left?**

We still need to do all the data entry for the opening hours of the buildings and incorporate that data into the bloc and the bottom sheet widget.

**Comment by DBatistaFerreira** [comment]
SGW Buildings with PopUp and Information
B ✅CB ✅CI ✅CL ✅D ✅EN ✅ER ✅EV ✅FA ✅FB ✅FG ✅GM✅GN ✅GS ✅H ✅K ✅LB ✅LD ✅LS ✅M ✅ MB ✅MI ✅MU ✅P ✅PR ✅Q ✅R ✅RR ✅S ✅SB ✅T ✅TD ✅V ✅VA ✅

X ❌Z ❌GA ❌ (will conditionally pass and fix in bug ticket)

Loyola Buildings with PopUp and Information
AD ✅BB ✅BH ✅CC ✅CJ ✅DO ✅FC ✅GE ✅HA ✅HB ✅HC ✅HU ✅JR ✅PC ✅PS ✅PT ✅PY ✅RA ✅RF ✅SC ✅SI ✅ SP ✅TA ✅VE ✅VL ✅

All buildings that have no opening hours just write unavailable ✅
Directions Button on every building ✅


Bugs Found
Highlighting Coordinates and Pop Up Information Missing Buildings #45
