### ISSUE TITLE
Concordia Building Selection

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#13]
# User Story 

## WHO/WHAT/WHY
* As a user, I want to be able to see all the SGW and Loyola buildings in a menu so that I can easily click on them and go to the building 

## ACCEPTANCE CRITERIA
* Menu to see all SGW and Loyola Buildings
* Clicking on any of them will bring you to the building

## IMPLEMENTATION NOTES
* SGW and Loyola will show different lists

**Comment by MoreWaqar** [comment]
![image](https://user-images.githubusercontent.com/35977219/74764078-0485e800-524f-11ea-9936-d18d145922e1.png)


![image](https://user-images.githubusercontent.com/35977219/74763990-d902fd80-524e-11ea-9c2e-b45fbe2b1159.png)

**Comment by danielwiktorczyk** [comment]
Will be replacing the current menu icons to better match the mock sent by Waqar above

**Comment by danielwiktorczyk** [comment]
![image](https://user-images.githubusercontent.com/24488852/75195196-7e264600-5727-11ea-8906-d58bf90e9c98.png)
Quick_Menu update. Will now add campus building list componeent

**Comment by danielwiktorczyk** [comment]
From building selection, move map to building, bring up popup

**Comment by danielwiktorczyk** [comment]
See branch #44

**Comment by danielwiktorczyk** [comment]
Updated menus with Icons of the Building Code, added list header. Awaiting Bloc Architecture issue for onTap() event, and design approval for margins, padding, etc
![image](https://user-images.githubusercontent.com/24488852/75297696-8a310700-57fe-11ea-988f-96d6c0905bf2.png)

**Comment by danielwiktorczyk** [comment]
Made the styling more uniform. Scoping out the search bar feature since it is low priority. 

Ready for QA review!
![image](https://user-images.githubusercontent.com/24488852/75368430-bf396a00-588f-11ea-8a99-80bf224023ba.png)

**Comment by DBatistaFerreira** [comment]
Acceptance Testing Passed ✔️

* Both Menu to see loyola and sgw buildings are there. All buildings are on these menus
* Clicking on them brings you to the building and puts a marker.

Bugs Raised: SGW and Loyola Markers not on building from the buildings menu #49
