### ISSUE TITLE
Outdoor Points of Interests 

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#15]
# User Story 

## WHO/WHAT/WHY
* As a user, I want to see points of interests around the campuses 

## ACCEPTANCE CRITERIA
* Screen that shows the outdoor points of interests
* Can search them outdoor points of interests
* Shows closest first

**Comment by MoreWaqar** [comment]
# Added backend logic for a hotspot in CGO#15.

A hotspot is defined with the following info:

  String address
  LatLng coordinates
  String hotspotName
  bool isOpen
  int priceLevel
  double rating
  HotspotType hotspotType

HotspotType is an enum that can easily be expanded to include more hotspot type. Currently consisting of:
Restaurant, Grocery, Shopping

**Comment by DBatistaFerreira** [comment]
Acceptance Testing Passed ✔️
Screen that shows the outdoor points of interests ✔️
* Restaurants, Grocery and Shopping Hotspots :) 
Can search them outdoor points of interests ✔️
* Can get any directions to them 
Shows closest first ✔️
