### ISSUE TITLE
Retrieve Schedule from Google Calendar 

### ISSUE THREAD

**Issue by danielwiktorczyk** [Pwnagebird/ConcordiaGO#16]
# User Story 

## WHO/WHAT/WHY
* As a user, I want to connect my Google Calendar so that my schedules and classes can be imported and synced

## ACCEPTANCE CRITERIA
* Saves users calendars data 
* Knows the date, time, class location 
* Indicate specific format for location for classroom
* UI for showing calendar

**Comment by DBatistaFerreira** [comment]
Acceptance Testing Passed ✔️

* Saves users calendars data✔️
* Knows the date, time, class location✔️
* Indicate specific format for location for classroom✔️
* UI for showing calendar✔️
https://www.youtube.com/watch?v=iMyodYzE-94&feature=youtu.be

Looks all good. Will be able to finish all the calendar requirements in sprint 4
