### ISSUE TITLE
Directions Algorithm with Concordia Shuttle Bus

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#19]
# User Story 

## WHO/WHAT/WHY
* As a user, I want to use the Concordia Shuttle Bus to get to my classes so that I can get to my destination quicker 

## ACCEPTANCE CRITERIA
*  In the directions algorithm if using the shuttle bus is quicker it will recommend this path

**Comment by MoreWaqar** [comment]
Code complete. Refactoring in process.

Meeting today with member responsible for Search UI revealed that shuttle bus and public transit will be two separate options and thus only one needs to be accommodate which reduces the total number of api calls and leads to faster execution time.

Variables need to be removed and refactoring done.

**Comment by DBatistaFerreira** [comment]
Acceptance Testing Passed ✔️

* As a user, I want to use the Concordia Shuttle Bus to get to my classes so that I can get to my destination quicker✔️
