### ISSUE TITLE
Shortest Path Class Directions

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#21]
# User Story 

## WHO/WHAT/WHY
* As a user, I want to see the shortest path directions from class to class.

## ACCEPTANCE CRITERIA
* Can input two classes 
* Shows me the shortest path between the two classes

#### __SUBTASKS__
- Load images onto the page (SVG or embed a bitmap using high-resolution rasterized asset images)[bitmap 0.0.6, flutter_svg 0.17.1]
- Manipulate the image (zoom, rotate)[photo_view 0.9.1, matrix_gesture_detector 0.1.0]
- Draw walls and nodes on loaded floor plans [bitmap 0.0.6, Canvas API]
- Draw lines from nodes on loaded floor plans [bitmap 0.0.6, Canvas API]
- Animate drawn lines [drawing_animation 0.1.3]
- Implement clickable POIs and classrooms on the asset floor plan
#### __dependencies__
+ bitmap 0.0.6
+ flutter_svg 0.17.1
+ photo_view 0.9.1
+ matrix_gesture_detector 0.1.0
+ drawing_animation 0.1.3
#### __SUBTASKS__
- Design non-negative weighted graphs
- Implement thread-safe priority queue [min-heap, heapq]
- Implement Dijkstra's algorithm using priority queue [queue]
- Design data controller [BLoC]
#### __imports__
+ queue
+ min-heap
+ heapq
+ namedtuple [from collections]

**Comment by neliop** [comment]
- "Be able to locate rooms (start or destination points) in the Indoor maps for a specific
floor"
- "Be able to show directions between rooms in different floors"
- "Indoor directions from SGW to Loyola and vice versa (or from Building to Building in the
same campus)"

**Comment by mteolis** [comment]
- Implemented a priority queue using a min heap.
- Designed and implemented a weighted graph for H8 floor plans with their matrix indices.

**Comment by mteolis** [comment]
#### Left to implement:
- floor to floor
- building to building

I will be uploading images of the floor plans with the steps for designing the nodes and edges on the floor plans.

**Comment by mteolis** [comment]
#### Floor Plan Graph Design Images
8th floor svg: https://cdn.discordapp.com/attachments/666625234757222401/689513481653059639/IMG_20200317_123916.jpg

Matrix edge connections:
https://cdn.discordapp.com/attachments/666625234757222401/689513505216528419/IMG_20200317_123938.jpg

**Comment by mteolis** [comment]
### Node IDs
#### Prefix
- 00 : Hallway
- 10 : Classrooms
- 11 : Stairs
- 12 : Escalators
- 13 : Elevators
- 14 : Tables
- 15 : Bathrooms
- 16 : Water fountains
- 17 : Security Desk
- 18 : Art
- 99 : Entrance/Exit

#### Hallway Nodes
- 000000
- 000001
- 000002
- 000003
...

#### Classrooms
- 100802
- 100803
- 100805
...

#### Stairs
- 110000
- 110001
...

#### Escalators
- 120000 (down)
- 120001 (up)

#### Elevators
- 130000
- 130001
...

#### Tables
- 140000
- 140001
...

#### Bathrooms
- 150000
- 150001
...

#### Water fountains
- 160000
- 160001
...

#### Exit
- 990000
- 990001
...

**Comment by mteolis** [comment]
#### Implemented
- Dijkstra's greedy shortest path algorithm.
- Unit tests for shortest path algorithm.

**Comment by DariushN** [comment]
**UI subtasks**

Implemented: 
- Floor change
- Path drawing on SVGs 

Left to implement: 
- Connection with shortest path algorithm
- UI finishing
- Widget testing

**Comment by mteolis** [comment]
#### Implemented
- H9 2D matrix
- H9 edge indices
- chain of responsibility for directions
- direction request
- direction object
- direction handler interface
- concrete direction handlers

**Comment by DBatistaFerreira** [comment]
Acceptance Testing Passed ✔️
* Can input two classes ✔️
* Shows me the shortest path between the two classes✔️
