### ISSUE TITLE
Floor Plans SVG Creation

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#24]
# Graphic Design Ticket

## WHO/WHAT/WHY
* Need Floor Map Templates for t

## ACCEPTANCE CRITERIA
* They all have same color schemes
* All room numbers are labeled 
* Rooms to Map
   * VL 1
   * VL 2
   * VE 1
   * VE 2
   * MB S2
   * MB 1
   * Hall 1 (Optional) 
   * Hall 2 (Optional)
   * Hall 8
   * Hall 9 
   * CC 1

## IMPLEMENTATION NOTES
* Vectr.com was used to create and edit the SVGs
* Classroom numbers are based on floor evacuation plans.
* Room numbers for staircases were omitted for implementation purposes.
* Hall 1 & 2 along with CC 1 were not realised and deemed optional.
* VL floor plans also show sections of VE floors as they did on the previous SVGs and evacuation plans.
* Same color scheme as UI mockups was used.

**Comment by bernzclav** [comment]
Here are the 8 floorplans. N.B.: SVGs were not accepted, so PNGs were uploaded instead.

![H8](https://user-images.githubusercontent.com/37311291/75615205-f5385180-5b0e-11ea-9121-eb6a2b133151.PNG)
![H9](https://user-images.githubusercontent.com/37311291/75615206-f5d0e800-5b0e-11ea-9c29-35672c2bbd41.PNG)
![MB1](https://user-images.githubusercontent.com/37311291/75615207-f6697e80-5b0e-11ea-9924-5c5ff37ad6af.PNG)
![MBS2](https://user-images.githubusercontent.com/37311291/75615208-f6697e80-5b0e-11ea-9a88-ac41cbe80c9d.PNG)
![VE1](https://user-images.githubusercontent.com/37311291/75615209-f7021500-5b0e-11ea-85b7-bff3f3dd6bb8.PNG)
![VE2](https://user-images.githubusercontent.com/37311291/75615210-f7021500-5b0e-11ea-8ada-0bfb95ebda39.png)
![VL1](https://user-images.githubusercontent.com/37311291/75615211-f79aab80-5b0e-11ea-891c-0ce878543368.PNG)
![VL2](https://user-images.githubusercontent.com/37311291/75615212-f79aab80-5b0e-11ea-88a3-cf8d3d780f5b.PNG)

**Comment by DBatistaFerreira** [comment]
These look awesome! Great job @bernzclav. Please post the original SVGs in discord so we can use them for the floor plans ticket. Closing this now
