### ISSUE TITLE
Indoor Point of Interest Icons Creation

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#25]
# User Story 

## WHO/WHAT/WHY
* Need Indoor POI Icons

## ACCEPTANCE CRITERIA
* All Icons for #14 are created
* Similar Color Scheme
* All Same Size Image

## IMPLEMENTATION NOTES
* Elevator, escalators, water, restrooms, IT help desk & emergency exits.
* All icons follow a black/white color scheme.
* All icons are of dimensions 128x128 and in PNG format.
* Icons made by Icon king from www.freeicons.io

**Comment by bernzclav** [comment]
Here are the 6 PNG files for the icons. SVGs also available if needed.

![Bathrooms](https://user-images.githubusercontent.com/37311291/75614672-34fc3a80-5b09-11ea-9f9c-8699fe90e9ba.png)
![Elevator](https://user-images.githubusercontent.com/37311291/75614673-362d6780-5b09-11ea-8a5e-a335acc573d4.png)
![EmergencyExit](https://user-images.githubusercontent.com/37311291/75614674-362d6780-5b09-11ea-8538-dfcd58c4ceb4.png)
![Escalators](https://user-images.githubusercontent.com/37311291/75614675-362d6780-5b09-11ea-83d2-369fa158d25c.png)
![ITDesk](https://user-images.githubusercontent.com/37311291/75614676-36c5fe00-5b09-11ea-9d19-b41d2afdea98.png)
![Water](https://user-images.githubusercontent.com/37311291/75614677-36c5fe00-5b09-11ea-8089-f212082d17f5.png)

**Comment by DBatistaFerreira** [comment]
These look good!, I'll accept them and we will change them if needed later on. Thanks @bernzclav
