### ISSUE TITLE
Software Architecture Initialization

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#28]
# To Do

* Class Diagram
* Component Diagram

* Textual Explanations on how Sprint 1 stories led to these diagrams

![image](https://user-images.githubusercontent.com/32440971/72303448-4e215880-363b-11ea-9d61-966ef86ded57.png)

**Comment by danielwiktorczyk** [comment]
Completed within the Deliverable Doc
