### ISSUE TITLE
Place to Place Outdoor Directions

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#33]
# User Story 

## WHO/WHAT/WHY
* As a user, I want to be able to get outdoor directions from place to place.

## ACCEPTANCE CRITERIA
* Show directions from any building to any building using google maps.
* Show the directions via the map
* Show another view to list the steps how to get there
* User can cancel the trip 
* User can complete the trip

**Comment by DBatistaFerreira** [comment]
Let's discuss if we can put the accessibility options

**Comment by MoreWaqar** [comment]
![image](https://user-images.githubusercontent.com/35977219/74991110-1b753780-5413-11ea-9b65-092bf3bf399e.png)

**Comment by DBatistaFerreira** [comment]
Acceptance Testing Passed ✔️

* Show directions from any building to any building using google maps. ✔️
* Show the directions via the map ✔️
* Show another view to list the steps how to get there ✔️
* User can cancel the trip ✔️
* User can complete the trip✔️

Looks all good. Search feature next sprint will definetly let us test this better
