### ISSUE TITLE
Indoor Pathing Algorithm

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#34]
# Spike

* Create a Wiki Page with all the Research
* If everything is okay, let @Pwnagebird  know and he will create a user story

## Some Research Topics 
* SVG Coordinate Fields 
* Algorithm to Detect Walls
* Shortest Path Algorithm
* Displaying On Google Maps 
...

**Comment by mteolis** [comment]
## __Indoor Navigation Screen__
* The indoor navigation will be handled on its own separate page named IndoorNavigationScreen.
* The page will be accessible from the app drawer.
* The page will display the specified floor plan from the selected building as an SVG image file.
* The origin and destination will be input provided by the user.

## __Dependencies__
###### flutter_svg 0.17.1
* Allow us to import and load SVG asset files in a page.

###### drawing_animation 0.1.3
* Provides animated drawing tools for drawing the lines from the origin point to the destination point.

###### photo_view 0.9.1
* Provides a zoomable image widget. Can be used as a container for SVG assets.

###### matrix_gesture_detector 0.1.0
* Provides a container that allows for the translation, rotation, and scaling of nested components (possibly SVG assets).

## __Shortest Path Algorithm__
### Algorithms
#### A* Search Algorithm
* A* (A-star) search algorithm provides shortest path for one destination for both unweighted and weighted graphs.

#### Dijkstra's Algorithm
* Provides shortest path for all destinations for weighted graphs without negative weights.

### Algorithm Time Complexities
#### A* Search Algorithm
_O_(_b_^_d_)
* b = branching factor (average number of descendants)
* d = shortest path (destination)

#### Dijkstra's Algorithm
###### Using Priority Queue
_O_(_N_^_2_)
* N = number of nodes

###### Using Binary Heap
_O_((_L_ _+_ _N_) _log_(_N_))
* L = number of links
* N = number of nodes

###### Using Fibonacci Heap
_O_(_L_ _+_ _N_ _log_(_N_))
* L = number of links
* N = number of nodes

#### Algorithm Implementation Data Structures
* Priority Queues
* Binary Heap
* Fibonacci Heap

## __Overview__
Using the dependencies listed above, the idea is to load in the appropriate floor plan SVG image asset, determined by the floor and building selected by the user, to the indoor navigation page. The SVG asset will be contained in a widget that provides zooming and rotating functionality. The directions from the point of origin to the destination point will be drawn on the SVG canvas using a Custom Painter, or possibly using drawing animations with Animated Painters.

As for the shortest path algorithm itself, it should be implemented using the data structure that best fits the needs of the app. This factor can be influenced by prioritizing either speed, accuracy, or space. The data structures will be created on the backend and perform the necessary computations to provide the user with the shortest path from their point of origin to their destination.
