### ISSUE TITLE
Highlighting Coordinates and Pop Up Information Missing Buildings

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#45]
# Description

* There seems to be missing buildings that are highlighted on the map (X, Z, GA)

## Expected Result
* X, Z, GA are highlighted on the map and can see their popup information

## Actual Result
* X, Z, GA are not highlighted 

## Steps
1. Open Application
2. Look for the X, Z, GA buildings on the map
3. They are not on the map

**Comment by danielwiktorczyk** [comment]
Please also examine other neighboring buildings. For example, building FA is not where it is expected to be found (at 2060 mackay)
![image](https://user-images.githubusercontent.com/24488852/76655174-1eaba100-6543-11ea-95a9-454d3d829205.png)

**Comment by DBatistaFerreira** [comment]
**Bug Fixed**
X, Z, GA are now highlighted
Services and Departments are there
