### ISSUE TITLE
SGW and Loyola Markers not on building from the buildings menu

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#49]
# Description
* Some of the markers are not in the correct places when clicking on buildings from buildings menu

## Expected Result
* All SGW and Loyola building markers should be in the center or near center of building when clicked on through the menu

## Actual Result
* Some SGW and Loyola building markers are not even on the buildings.
* ex, Stinger Dome, JR, FC... etc

## Steps
1. Open application
2. Click on menu
3. Click on Loyola Buildings
4. Select Stinger Dome
5. View where the marker is vs where the building is.

**Comment by danielwiktorczyk** [comment]
I added the locations according to the concordia website resource for buildings. 
Are we instead preferring to stick with placing the markers at the center of our polygons?

**Comment by danielwiktorczyk** [comment]
After discussion with the team, we have agreed that we will placing the markers towards the center of the building vertices, so this bug remains to be done

**Comment by DBatistaFerreira** [comment]
**Bug Fixed**
All Markers go on buildings and within the highlighting
