### ISSUE TITLE
End of Directions Screen

### ISSUE THREAD

**Issue by DBatistaFerreira** [Pwnagebird/ConcordiaGO#73]
# Description
* When I'm finished my directions I get no feedback that I'm done

## Expected Result
* End of Directions Screen (You're Here!)

## Actual Result
* Just gets stuck on last direction with an arrow to keep going

## Steps
1. Open Application
2. Open Directions Screen
3. Select Directions
4. Go To Last Direction
5. Arrow that does nothing -->

**Comment by neliop** [comment]
We should implement feedback upon reaching destination in Sprint 4.

**Comment by danielwiktorczyk** [comment]
_Addition: for outdoor directions, make the start and end points of the line have a source and destination icon, like the current ones for indoor directions. Point brought up by @Debnam_ 

Edit: Choosing not to do, since 1. User current location is shown, 2. current step segment is zoomed / focused in on, and 3. requirement was not originally in ticket

**Comment by danielwiktorczyk** [comment]
Updated the outdoor directions UI as such to avoid forward / backward buttons that do nothing: 

Screen with starting step:
![image](https://user-images.githubusercontent.com/24488852/79053941-2710fd80-7c0f-11ea-85ff-b092fe72676d.png)

Screen when midway through outdoor directions:
![image](https://user-images.githubusercontent.com/24488852/79053948-2e380b80-7c0f-11ea-9a43-005af1e7dac3.png)

Screen when the final instruction is reached, and is outside:
![image](https://user-images.githubusercontent.com/24488852/79053954-36904680-7c0f-11ea-952e-dfa697fa6649.png)

Screen with indoor directions as the next step:
![image](https://user-images.githubusercontent.com/24488852/79053968-53c51500-7c0f-11ea-811d-364599bd368c.png)

Also, updated UI Directions Test

**Comment by DBatistaFerreira** [comment]
Acceptance Testing Passed ✔️

Indication of end of my journey ✔️
